### ISSUE TITLE
Нужна возможность настройки отправки сообщений в telegram с программы.

### ISSUE THREAD

**Issue by kudryaA** [Maxuha/NCTaskManager#8]
Сейчас чат отправки сообщений прописан прям в коде.

**Comment by Maxuha** [comment]
Исправил. Теперь достаточно отправить боту любое сообщение, и программа создаст файл(если он ещё не создан) с ChatId. Таки образом ChatId программа берет с файла. Токен зашифрован. Необходимо расшифровать(способами git-secret) и положить в файл toket_telegram_bot.txt. Также это описано в README.
